name: Deploy Site on push - develop
on:
  push:
    branches:
      - develop
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get the latest code
        uses: actions/checkout@v2.3.2
      - name: Sync files to server using sftp
        uses: wangyucode/sftp-upload-action@v1.1
        with:
          host: ${{ secrets.SSH_HOST }}
          port: 22
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PRIVATE_KEY }}
          localDir: /
          remoteDir: ${{ secrets.DEV_REMOTE_LOCATION }}
          dryRun: false
      - name: Deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          password: ${{ secrets.SSH_PRIVATE_KEY }}
          username: ${{ secrets.SSH_USERNAME }}
          script: |
            cd ${{ secrets.DEV_REMOTE_LOCATION }}
            cp .env.example .env
            chmod 777 -R bootstrap
            chmod 777 -R storage
            composer install
            echo ${{ secrets.SSH_PRIVATE_KEY }} | sudo vendor/bin/sail down
            sudo vendor/bin/sail up -d
            sudo vendor/bin/sail artisan migrate:refresh --seed
            sudo vendor/bin/sail artisan storage:link